### ISSUE TITLE
Error with earthengine authenticate

### ISSUE THREAD

**Issue by slandersson** [mortcanty/earthengine#2]
Hi Mort,

I got an error whilst authenticating using the docker image, I wonder if you have run into this before?
If not I will try a couple of other machines then post it on the GEE dev group.

Cheers!
Simon

```

root@aaa18636a528:/home# python -c "import ee; ee.Initialize()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "ee/__init__.py", line 90, in Initialize
    credentials = _GetPersistentCredentials()
  File "ee/_helpers.py", line 41, in _GetPersistentCredentials
    raise EEException('Please authorize access to your Earth Engine account '
ee.ee_exception.EEException: Please authorize access to your Earth Engine account by running


earthengine authenticate


in your command line, and then retry.
root@aaa18636a528:/home# earthengine authenticate
Traceback (most recent call last):
  File "/usr/local/bin/earthengine", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 645, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2401, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2597, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2630, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2627, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/usr/lib/python2.7/dist-packages/_markerlib/markers.py", line 113, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'python_implementation' is not defined
```

**Comment by mortcanty** [comment]
Haven't seen it before and can't reproduce it now on my machine with the current docker image:

root@d6b4676400da:/home# earthengine authenticate

    Opening web browser to address https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fearthengine+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&client_id=517222506229-vsmmajv00ul0bs7p89v5m89qs8eb9359.apps.googleusercontent.com
    Please authorize access to your Earth Engine account, and paste
    the resulting code below.
    If the web browser does not start, please manually browse the URL above.
          
Please enter authorization code: 4/1M4aikLdi2fha6uGf3T_UDIG9lHtl9Vz1CmnRdcMS8M

Successfully saved authorization token.
root@d6b4676400da:/home# ./app.py
 * Running on http://0.0.0.0:5000/
 * Restarting with reloader

Mort

**Comment by slandersson** [comment]
Thanks for replying so quickly.
```
root@190b9b15c75f:/home# ./app.py
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
```

In the end the fix was to uninstall and re-install python on the docker image I was running.
Now to have a dig into the app!

Simon

**Comment by xyzromero** [comment]
hi Mort,
I authenticate my earthengine but i thin i need somthing more to run the script in the docker container which i follow from the book  (Image Analysis, Classification, and Change Detection in Remote Sensing With Algorithms for Python Fourth edition) i take theese pictures of the error 
![homework cont](https://user-images.githubusercontent.com/70040187/90941252-31ba7b00-e3d7-11ea-82d7-4f0047b11039.PNG)
![homework](https://user-images.githubusercontent.com/70040187/90941253-32531180-e3d7-11ea-9a90-073247b64082.PNG)
